import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavComponent } from "@/components/nav";
import { AboutComponent } from "@/components/about";
import { BackgroundComponent } from "@/components/background";
import { ExperienceComponent } from "@/components/experience";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark antialiased min-h-screen flex`}
      >
        <BackgroundComponent />
        <main className="flex-1 relative z-20 flex items-center justify-center">
          <NavComponent />
          <div className="max-w-5xl">
            <AboutComponent />
            <ExperienceComponent />
          </div>
        </main>
        {children}
      </body>
    </html>
  );
}
