name: compile_cv
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: true
      - name: Generate CV
        run: pnpm run cv-gen
      - name: Compile CV
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv_rendered.tex
          texlive_version: 2026
          working_directory: ./cv/build
      - name: Rename CV
        run: cp ./cv/build/cv_rendered.pdf ./cv/build/CV_Dimitrie-Toma_Furdui.pdf
      - name: Upload CV
        uses: actions/upload-artifact@v7
        with:
          name: CV_Dimitrie-Toma_Furdui.pdf
          path: ./cv/build/cv_rendered.pdf
          archive: false
